/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'Contexte',
    'Architecture',
    {
      type: 'category',
      label: 'Analyse',
      items: [
        'Persona',
        'User Journey',
        'Pain points',
        'Features'
      ],
    },
    {
      type: 'category',
      label: 'Développement',
      items: [
        'Méthodologie',
        'Structure du projet',
        'Stack technique',
        'Tests',
        'Base de données',
        'Documentation Swagger'
      ],
    },
    "Manuel d'installation",
    "Manuel d'utilisation"
  ],
   
};

module.exports = sidebars;
